/**
 * Mock data for offboarding functionality
 * This provides demo data for templates, processes, and tasks
 */

export const mockOffboardingTemplates = [
  {
    id: 'tmpl-001',
    name: 'Standard Employee Offboarding',
    description: 'Standard process for regular employee departures with basic handover requirements',
    template_type: 'company_wide',
    department: null,
    role_category: null,
    seniority_level: 'all',
    estimated_duration_days: 14,
    complexity_score: 2,
    task_count: 12,
    usage_count: 45,
    is_default: true,
    requires_manager_approval: true,
    requires_hr_approval: false,
    requires_security_review: false,
    created_at: '2024-01-15T10:00:00Z'
  },
  {
    id: 'tmpl-002',
    name: 'Engineering Department Offboarding',
    description: 'Specialized process for engineering team members including code review and system access',
    template_type: 'department_specific',
    department: 'Engineering',
    role_category: 'technical',
    seniority_level: 'mid_level',
    estimated_duration_days: 21,
    complexity_score: 4,
    task_count: 18,
    usage_count: 12,
    is_default: false,
    requires_manager_approval: true,
    requires_hr_approval: true,
    requires_security_review: true,
    created_at: '2024-02-01T14:30:00Z'
  },
  {
    id: 'tmpl-003',
    name: 'Sales Team Offboarding',
    description: 'Client relationship handover focused process with emphasis on account transitions',
    template_type: 'department_specific',
    department: 'Sales',
    role_category: 'client_facing',
    seniority_level: 'senior',
    estimated_duration_days: 10,
    complexity_score: 3,
    task_count: 15,
    usage_count: 8,
    is_default: false,
    requires_manager_approval: true,
    requires_hr_approval: false,
    requires_security_review: false,
    created_at: '2024-03-10T09:15:00Z'
  },
  {
    id: 'tmpl-004',
    name: 'Executive Offboarding',
    description: 'High-level offboarding process for C-suite and VP positions with board notifications',
    template_type: 'role_specific',
    department: null,
    role_category: 'executive',
    seniority_level: 'executive',
    estimated_duration_days: 30,
    complexity_score: 5,
    task_count: 25,
    usage_count: 3,
    is_default: false,
    requires_manager_approval: true,
    requires_hr_approval: true,
    requires_security_review: true,
    requires_legal_review: true,
    created_at: '2024-01-20T11:00:00Z'
  },
  {
    id: 'tmpl-005',
    name: 'Remote Employee Offboarding',
    description: 'Process for remote workers including equipment return logistics and virtual handovers',
    template_type: 'custom',
    department: null,
    role_category: null,
    seniority_level: 'all',
    estimated_duration_days: 16,
    complexity_score: 3,
    task_count: 14,
    usage_count: 20,
    is_default: false,
    requires_manager_approval: true,
    requires_hr_approval: false,
    requires_security_review: true,
    created_at: '2024-04-05T13:20:00Z'
  }
];

export const mockOffboardingProcesses = [
  // Active processes
  {
    id: 'proc-001',
    process_name: 'John Smith Offboarding',
    template_id: 'tmpl-002',
    employee_id: 'emp-001',
    employee_name: 'John Smith',
    employee_department: 'Engineering',
    employee_position: 'Senior Software Engineer',
    status: 'active',
    priority: 'standard',
    completion_percentage: 45,
    target_completion_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    actual_start_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    actual_completion_date: null,
    overdue_tasks: 1,
    total_tasks: 18,
    completed_tasks: 8,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_by: 'manager@company.com'
  },
  {
    id: 'proc-002',
    process_name: 'Sarah Johnson Offboarding',
    template_id: 'tmpl-003',
    employee_id: 'emp-002',
    employee_name: 'Sarah Johnson',
    employee_department: 'Sales',
    employee_position: 'Account Manager',
    status: 'pending_approval',
    priority: 'urgent',
    completion_percentage: 0,
    target_completion_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    actual_start_date: null,
    actual_completion_date: null,
    overdue_tasks: 0,
    total_tasks: 15,
    completed_tasks: 0,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_by: 'hr@company.com'
  },
  {
    id: 'proc-003',
    process_name: 'Mike Wilson Offboarding',
    template_id: 'tmpl-001',
    employee_id: 'emp-003',
    employee_name: 'Mike Wilson',
    employee_department: 'Marketing',
    employee_position: 'Marketing Specialist',
    status: 'active',
    priority: 'high',
    completion_percentage: 72,
    target_completion_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    actual_start_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    actual_completion_date: null,
    overdue_tasks: 0,
    total_tasks: 12,
    completed_tasks: 9,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    created_by: 'manager@company.com'
  },
  {
    id: 'proc-004',
    process_name: 'Emily Chen Offboarding',
    template_id: 'tmpl-004',
    employee_id: 'emp-004',
    employee_name: 'Emily Chen',
    employee_department: 'Executive',
    employee_position: 'VP of Operations',
    status: 'active',
    priority: 'urgent',
    completion_percentage: 20,
    target_completion_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    actual_start_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    actual_completion_date: null,
    overdue_tasks: 2,
    total_tasks: 25,
    completed_tasks: 5,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_by: 'ceo@company.com'
  },
  // Recently completed
  {
    id: 'proc-005',
    process_name: 'David Brown Offboarding',
    template_id: 'tmpl-001',
    employee_id: 'emp-005',
    employee_name: 'David Brown',
    employee_department: 'Finance',
    employee_position: 'Financial Analyst',
    status: 'completed',
    priority: 'standard',
    completion_percentage: 100,
    target_completion_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    actual_start_date: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    actual_completion_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    overdue_tasks: 0,
    total_tasks: 12,
    completed_tasks: 12,
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    created_by: 'manager@company.com'
  },
  {
    id: 'proc-006',
    process_name: 'Lisa Anderson Offboarding',
    template_id: 'tmpl-005',
    employee_id: 'emp-006',
    employee_name: 'Lisa Anderson',
    employee_department: 'Customer Success',
    employee_position: 'Customer Success Manager',
    status: 'completed',
    priority: 'low',
    completion_percentage: 100,
    target_completion_date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    actual_start_date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    actual_completion_date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    overdue_tasks: 0,
    total_tasks: 14,
    completed_tasks: 14,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    created_by: 'hr@company.com'
  },
  // On hold
  {
    id: 'proc-007',
    process_name: 'Robert Taylor Offboarding',
    template_id: 'tmpl-002',
    employee_id: 'emp-007',
    employee_name: 'Robert Taylor',
    employee_department: 'Engineering',
    employee_position: 'DevOps Engineer',
    status: 'on_hold',
    priority: 'standard',
    completion_percentage: 35,
    target_completion_date: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    actual_start_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    actual_completion_date: null,
    overdue_tasks: 0,
    total_tasks: 18,
    completed_tasks: 6,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    created_by: 'manager@company.com',
    hold_reason: 'Employee requested extension due to critical project completion'
  }
];

export const mockOffboardingTasks = [
  // Tasks for John Smith (proc-001)
  {
    id: 'task-001',
    process_id: 'proc-001',
    task_name: 'Return laptop and equipment',
    description: 'Collect and inventory all company equipment including laptop, monitor, and accessories',
    status: 'completed',
    priority: 'high',
    assigned_to: 'IT Department',
    due_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    completed_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    estimated_hours: 1,
    actual_hours: 0.5,
    task_order: 1,
    dependencies: [],
    documents_required: ['Equipment Checklist', 'Return Receipt']
  },
  {
    id: 'task-002',
    process_id: 'proc-001',
    task_name: 'Knowledge transfer - Authentication System',
    description: 'Transfer critical knowledge about the custom authentication system to the team',
    status: 'in_progress',
    priority: 'critical',
    assigned_to: 'John Smith',
    due_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    completed_date: null,
    estimated_hours: 4,
    actual_hours: 2,
    task_order: 2,
    dependencies: ['task-001'],
    documents_required: ['Knowledge Transfer Template', 'Technical Documentation']
  },
  {
    id: 'task-003',
    process_id: 'proc-001',
    task_name: 'Code repository access removal',
    description: 'Remove access to all code repositories and development environments',
    status: 'pending',
    priority: 'critical',
    assigned_to: 'Security Team',
    due_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    completed_date: null,
    estimated_hours: 0.5,
    actual_hours: 0,
    task_order: 3,
    dependencies: ['task-002'],
    documents_required: ['Access Revocation Form']
  },
  {
    id: 'task-004',
    process_id: 'proc-001',
    task_name: 'Exit interview',
    description: 'Conduct comprehensive exit interview to gather feedback',
    status: 'blocked',
    priority: 'medium',
    assigned_to: 'HR Department',
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    completed_date: null,
    estimated_hours: 1,
    actual_hours: 0,
    task_order: 4,
    dependencies: [],
    documents_required: ['Exit Interview Form', 'Feedback Survey'],
    blocked_reason: 'Waiting for employee availability'
  },
  {
    id: 'task-005',
    process_id: 'proc-001',
    task_name: 'Final payroll processing',
    description: 'Calculate and process final paycheck including unused PTO',
    status: 'pending',
    priority: 'high',
    assigned_to: 'Payroll Team',
    due_date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    completed_date: null,
    estimated_hours: 2,
    actual_hours: 0,
    task_order: 5,
    dependencies: [],
    documents_required: ['Final Pay Calculation', 'PTO Balance Report']
  },
  // Tasks for Mike Wilson (proc-003)
  {
    id: 'task-010',
    process_id: 'proc-003',
    task_name: 'Marketing assets handover',
    description: 'Transfer ownership of all marketing campaigns and creative assets',
    status: 'completed',
    priority: 'high',
    assigned_to: 'Mike Wilson',
    due_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    completed_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    estimated_hours: 3,
    actual_hours: 2.5,
    task_order: 1,
    dependencies: [],
    documents_required: ['Asset Inventory', 'Campaign Documentation']
  },
  {
    id: 'task-011',
    process_id: 'proc-003',
    task_name: 'Social media account transition',
    description: 'Transfer admin access for all company social media accounts',
    status: 'completed',
    priority: 'critical',
    assigned_to: 'Marketing Team',
    due_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    completed_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    estimated_hours: 1,
    actual_hours: 1,
    task_order: 2,
    dependencies: [],
    documents_required: ['Account Access List']
  },
  {
    id: 'task-012',
    process_id: 'proc-003',
    task_name: 'Email account deactivation',
    description: 'Set up email forwarding and schedule account deactivation',
    status: 'in_progress',
    priority: 'high',
    assigned_to: 'IT Department',
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    completed_date: null,
    estimated_hours: 0.5,
    actual_hours: 0,
    task_order: 3,
    dependencies: [],
    documents_required: ['Email Forwarding Setup']
  },
  // Tasks for Emily Chen (proc-004)
  {
    id: 'task-020',
    process_id: 'proc-004',
    task_name: 'Board notification',
    description: 'Formally notify the board of directors about executive departure',
    status: 'completed',
    priority: 'critical',
    assigned_to: 'CEO',
    due_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    completed_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    estimated_hours: 2,
    actual_hours: 2,
    task_order: 1,
    dependencies: [],
    documents_required: ['Board Communication Template']
  },
  {
    id: 'task-021',
    process_id: 'proc-004',
    task_name: 'Strategic initiatives handover',
    description: 'Document and transfer all ongoing strategic initiatives and projects',
    status: 'in_progress',
    priority: 'critical',
    assigned_to: 'Emily Chen',
    due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    completed_date: null,
    estimated_hours: 8,
    actual_hours: 3,
    task_order: 2,
    dependencies: [],
    documents_required: ['Strategic Plan', 'Project Status Reports']
  },
  {
    id: 'task-022',
    process_id: 'proc-004',
    task_name: 'Executive team transition meeting',
    description: 'Conduct transition meeting with remaining executive team members',
    status: 'pending',
    priority: 'high',
    assigned_to: 'CEO',
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    completed_date: null,
    estimated_hours: 2,
    actual_hours: 0,
    task_order: 3,
    dependencies: ['task-021'],
    documents_required: ['Transition Plan', 'Org Structure Update']
  },
  {
    id: 'task-023',
    process_id: 'proc-004',
    task_name: 'Legal document review',
    description: 'Review and update all legal documents related to executive departure',
    status: 'pending',
    priority: 'critical',
    assigned_to: 'Legal Department',
    due_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    completed_date: null,
    estimated_hours: 4,
    actual_hours: 0,
    task_order: 4,
    dependencies: [],
    documents_required: ['Separation Agreement', 'NDA Updates'],
    overdue: true
  }
];

// Helper function to get mock data
export function getMockOffboardingData() {
  return {
    templates: mockOffboardingTemplates,
    processes: mockOffboardingProcesses,
    tasks: mockOffboardingTasks
  };
}

// Helper function to get tasks for a specific process
export function getTasksForProcess(processId) {
  return mockOffboardingTasks.filter(task => task.process_id === processId);
}

// Helper function to get template by ID
export function getTemplateById(templateId) {
  return mockOffboardingTemplates.find(template => template.id === templateId);
}